apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: mhmmdsyahputra/notes-app:2.0
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: notes-app
  ports:
    - port: 8080
      targetPort: 80
